// 05-metaframeworks/nuxt/app/components/house-detail/HouseDetailOverview.vue
<script setup lang="ts">
import type { Component } from "vue";

interface Characteristic {
  icon: Component;
  label: string;
  value: number;
}

interface Props {
  description: string;
  houseCharacteristics: Characteristic[];
}

defineProps<Props>();
</script>

<template>
  <div class="flex flex-col gap-6">
    <p class="text-neutral-400 leading-relaxed">{{ description }}</p>
    <ol class="flex flex-col gap-2">
      <li
        v-for="characteristic in houseCharacteristics"
        :key="characteristic.label"
        class="flex items-center gap-2"
      >
        <component
          :is="characteristic.icon"
          class="w-4 h-4 text-emerald-500"
        />
        <span>{{ characteristic.value }}</span>
        <span>{{ characteristic.label }}</span>
      </li>
    </ol>
  </div>
</template>

// 05-metaframeworks/tanstack-start/src/components/house-detail/house-detail-overview.tsx
import type { LucideIcon } from "lucide-react";

interface Characteristic {
  icon: LucideIcon;
  label: string;
  value: number;
}

interface Props {
  description: string;
  houseCharacteristics: Characteristic[];
}

export function HouseDetailOverview(props: Props) {
  const { description, houseCharacteristics } = props;

  return (
    <div className="flex flex-col gap-6">
      <p className="text-neutral-400 leading-relaxed">{description}</p>
      <ol className="flex flex-col gap-2">
        {houseCharacteristics.map((characteristic) => {
          const Icon = characteristic.icon;
          return (
            <li key={characteristic.label} className="flex items-center gap-2">
              <Icon className="w-4 h-4 text-cyan-500" />
              <span>{characteristic.value}</span>
              <span>{characteristic.label}</span>
            </li>
          );
        })}
      </ol>
    </div>
  );
}
