// 05-metaframeworks/nuxt/app/components/house-detail/HouseDetailReviews.vue
<script setup lang="ts">
import type { Review } from "~/types";

interface Props {
  reviews: Review[];
}

defineProps<Props>();
</script>

<template>
  <div v-if="reviews.length > 0" class="flex flex-col gap-4">
    <div class="flex items-center gap-2">
      <h2 class="text-lg font-bold text-neutral-100">Reseñas</h2>
      <span class="text-neutral-500">({{ reviews.length }})</span>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
      <ReviewCard
        v-for="review in reviews"
        :key="review.id"
        :review="review"
      />
    </div>
  </div>
</template>

// 05-metaframeworks/tanstack-start/src/components/house-detail/house-detail-reviews.tsx
import type { Review } from "@/types";
import { ReviewCard } from "../review-card";

interface Props {
  reviews: Review[];
}

export function HouseDetailReviews(props: Props) {
  const { reviews } = props;

  if (reviews.length === 0) return null;

  return (
    <div className="flex flex-col gap-4">
      <div className="flex items-center gap-2">
        <h2 className="text-lg font-bold text-neutral-100">Reseñas</h2>
        <span className="text-neutral-500">({reviews.length})</span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {reviews.map((review) => (
          <ReviewCard key={review.id} review={review} />
        ))}
      </div>
    </div>
  );
}
