// 04-frameworks/react/src/layouts/components/navbar.component.tsx
import { switchRoutes } from "@/core";
import { Link, NavLink } from "react-router";

const NavbarComponent = () => {
  const labs = [
    {
      id: "organizations",
      label: "Organizations",
      to: switchRoutes.organizations,
    },
    {
      id: "members",
      label: "Members",
      to: switchRoutes.organizationMembers,
    },
  ];
  return (
    <nav className="flex items-center justify-between p-4 py-3 bg-zinc-900">
      <Link to={switchRoutes.root}>
        <h1 className="text-2xl font-bold">React Labs</h1>
      </Link>

      <ul className="flex items-center gap-4">
        {labs.map((lab) => (
          <li key={lab.id}>
            <NavLink
              key={lab.label}
              to={lab.to}
              className={({ isActive }) =>
                isActive
                  ? "text-white font-medium bg-zinc-800 px-2 py-1 rounded-md"
                  : "text-zinc-400 hover:text-white font-medium"
              }
            >
              {lab.label}
            </NavLink>
          </li>
        ))}
      </ul>
    </nav>
  );
};

export default NavbarComponent;

// 04-frameworks/vue/src/components/nav-bar.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router'
import { routes } from '@/router/routes'
</script>

<template>
  <nav class="mx-auto flex w-full max-w-7xl items-center justify-between gap-6 py-4 px-6">
    <h1 class="text-xl font-black tracking-[0.2em] text-zinc-100 uppercase sm:text-2xl">
      weekly meal
    </h1>
    <ul class="flex items-center gap-2 text-sm font-medium text-zinc-300 sm:gap-4 sm:text-base">
      <li v-for="route in Object.values(routes)" :key="route.path">
        <RouterLink
          :to="route.path"
          class="rounded-md px-3 py-2 transition-colors duration-200 hover:bg-zinc-800 hover:text-zinc-100"
          active-class="bg-zinc-800 text-zinc-100"
        >
          {{ route.label }}
        </RouterLink>
      </li>
    </ul>
  </nav>
</template>
